### ISSUE TITLE
discuss & create code of conduct for DEI meetings

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/hackweek-2021#8]
I don't believe we've ever talked as a lab about how to have these conversations. We can discuss how best to have DEI meetings with each other and create a sort of code of conduct document about expected behavior, proper language to use for certain topics... etc.

**Comment by yaaminiv** [comment]
here's what we had for the FISH 507 class:

We are dedicated to providing a welcoming and supportive environment for all people, regardless of background, identity, physical appearance, or manner of communication. Any form of language or behavior used to exclude, intimidate, or cause discomfort will not be tolerated. This applies to all course participants (instructor, students, guests). In order to foster a positive and professional learning environment, we will be using progressive stack discussion methods and these discussion rules:

- We will listen with the intention of understanding.
- We will monitor our own air time (aim to share the space and time so others may participate as well).
- We will respect those who do not wish to speak.
- We will use “I” statements as opposed to generalizations.
- We will not ask anyone to speak on behalf of any group we perceive them to identify with, or that they self-identify with
- We will expect discomfort.
- We will resist the urge to “fix” others’ discomfort.
- We will elevate impact above intent, and we will apologize when necessary.
- We will expect and accept non-closure. We acknowledge that these conversations may not be resolved in a single meeting.
- We will take lessons learned, but not others’ stories, out of this space.
- We will not participate in ad hominem attacks.

**Comment by sr320** [comment]
added to handbook
