### ISSUE TITLE
create log of DEI topics and resources

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/hackweek-2021#9]
not sure if interest, but I started a log spreadsheet of topics with links to resources shared

might be easier to refer back to than scrolling through slack channel? 

link to start of spreadsheet here: https://docs.google.com/spreadsheets/d/1LCIiAqWMaJ0tPZIevUXqWyZR2SN4p9qGLgQIvWBaWgo/edit?usp=sharing 

feel free to make any changes to sheet

**Comment by aspencoyle** [comment]
Alright, this should be complete! A few caveats:

- I wasn't able to get further back in time than Oct. 28, 2020 (I was just scrolling back through the slack channel, and that's when access stops). So we're missing a solid chunk of time

- Since I was using slack and didn't want to be cross-referencing a calendar, the  "dates" column refers to the date the person *posted* the topic, not when it was actually discussed. 

Otherwise, we've got everything up to the present!

**Comment by sr320** [comment]
added link to handbook https://robertslab.github.io/resources/Environment-and-Expectations/
